### ISSUE TITLE
Html equation doesn t work

### ISSUE THREAD

**Issue by pommedeterresautee** [petrkeil/Blog#1]
I use Chrome.

I see that on html file (yours, posted on your blog) :

```
Equations
The deterministic part of the model is defined by this in-line equation as [Math Processing Error], and the stochastic part by the centered equation:

[Math Processing Error]
```

**Comment by pommedeterresautee** [comment]
Made some test, result is good in Rstudio, but not on Explorer (I see the forumula in Latex) or Chrome (error message) ...

May be an issue with Windows

**Comment by pommedeterresautee** [comment]
http://tex.stackexchange.com/questions/174766/math-processing-error-when-processing-latex-using-knitr-in-r?rq=1 may help...

**Comment by pommedeterresautee** [comment]
Final solution : maj F5 

Well known bug, may be should publish something on your website for others like me.

http://meta.math.stackexchange.com/questions/3627/why-is-math-processing-error-all-over-the-place-today

**Comment by petrkeil** [comment]
Hi,
thanks for all the testing :-)
Yes, I maybe should insert a note on that.
Petr
